events {}
http {
    server {
        listen 80;
        server_name transit-api.transitco.in admin.transitco.in;
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
        location / { return 200 'ok'; }
    }
}
