import { Router } from 'express';
import { authenticateAdmin, requireRole } from '../middleware/auth';
import { getDashboardStats, listPlans, createPlan, updatePlan, schedulePriceChange, cancelScheduledChange, createPriceOverride, listDrivers, getDriver, updateDriverKyc, suspendDriver, listFareRules, createFareRule, updateFareRule, updateSurge, listRides, getAnalytics } from '../controllers/admin.controller';
const r = Router();
r.use(authenticateAdmin);
r.get('/dashboard/stats', getDashboardStats);
r.get('/analytics', getAnalytics);
r.get('/subscriptions/plans', listPlans);
r.post('/subscriptions/plans', requireRole('SUPER_ADMIN', 'CITY_ADMIN'), createPlan);
r.patch('/subscriptions/plans/:id', requireRole('SUPER_ADMIN', 'CITY_ADMIN'), updatePlan);
r.post('/subscriptions/plans/:id/schedule', requireRole('SUPER_ADMIN', 'CITY_ADMIN'), schedulePriceChange);
r.delete('/subscriptions/schedules/:scheduleId', requireRole('SUPER_ADMIN'), cancelScheduledChange);
r.post('/subscriptions/override', requireRole('SUPER_ADMIN', 'CITY_ADMIN'), createPriceOverride);
r.get('/drivers', listDrivers);
r.get('/drivers/:id', getDriver);
r.patch('/drivers/:id/kyc', requireRole('SUPER_ADMIN', 'CITY_ADMIN'), updateDriverKyc);
r.patch('/drivers/:id/suspend', requireRole('SUPER_ADMIN'), suspendDriver);
r.get('/fare-rules', listFareRules);
r.post('/fare-rules', requireRole('SUPER_ADMIN'), createFareRule);
r.patch('/fare-rules/:id', requireRole('SUPER_ADMIN'), updateFareRule);
r.patch('/fare-rules/:id/surge', requireRole('SUPER_ADMIN', 'CITY_ADMIN'), updateSurge);
r.get('/rides', listRides);
export default r;
